openapi: 3.1.0
info:
  title: Supply Chain Track and Trace API
  version: 1.0.0
  description: API for managing supply chain items and events

servers:
  - url: http://localhost:3000

paths:
  /api/items:
    post:
      summary: Create a new supply chain item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

  /api/items/{id}:
    get:
      summary: Get supply chain item details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Not Found

    put:
      summary: Update supply chain item reference data
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemUpdateInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Not Found

  /api/items/{id}/events:
    post:
      summary: Add a new event to an item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Not Found

    get:
      summary: Get all events of an item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '404':
          description: Not Found

  /api/items/search:
    get:
      summary: Search for items by name
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'

components:
  schemas:
    ItemInput:
      type: object
      required:
        - id
        - name
        - color
        - price
      properties:
        id:
          type: string
        name:
          type: string
        color:
          type: string
        price:
          type: number

    ItemUpdateInput:
      type: object
      properties:
        color:
          type: string
        price:
          type: number

    Item:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        color:
          type: string
        price:
          type: number
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'

    EventInput:
      type: object
      required:
        - location
        - custodian
      properties:
        location:
          type: string
        custodian:
          type: string

    Event:
      type: object
      properties:
        location:
          type: string
        custodian:
          type: string
        timestamp:
          type: string
          format: date-time